default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: db
  pool: 5

development:
  <<: *default
  database: rails_react_developments

test:
  <<: *default
  database: rails_react_test

production:
  primary: &primary_production
    <<: *default
    database: rails_react_production
    username: rails_react
    password: <%= ENV["RAILS_REACT_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: rails_react_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rails_react_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rails_react_production_cable
    migrations_paths: db/cable_migrate
